### ISSUE TITLE
Assertion Error (expecting symmetric matrix) only happening for some MSMs?

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/msm-pipeline#12]
So far this is has only happened in one of the three MSMs I'm building right now:

```
    super(StreamingTransformer, self).estimate(X, **kwargs)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py", line 348, in estimate
    self._model = self._estimate(X)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/transform/tica.py", line 297, in _estimate
    self._diagonalize()
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/transform/tica.py", line 308, in _diagonalize
    eigenvalues, eigenvectors = eig_corr(self.cov, self.cov_tau, self.epsilon)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/util/linalg.py", line 151, in eig_corr
    assert np.allclose(C0.T, C0), 'C0 is not a symmetric matrix'
AssertionError: C0 is not a symmetric matrix
```

**Comment by jchodera** [comment]
Can you report this on the pyemma issue tracker?

**Comment by sonyahanson** [comment]
Getting this error now for both CK2 and SYK projects even when running on trajectories copied to a local folder...

**Comment by jchodera** [comment]
Can you paste more of that error? It looks like you've snipped out the part of the stack trace that starts in our code---all of those lines are in `pyemma`.

**Comment by sonyahanson** [comment]
```
Running pipeline
Finding respairs_that_changed...
Number of contacts that changed: 13728
Total number of possible contacts: 53956
calculate mean+cov: 100% (1591/1591) [#############################] eta 00:00 |Traceback (most recent call last):
  File "pipeline.py", line 190, in <module>
    run_pipeline(fnames, project_name = project_name)
  File "pipeline.py", line 101, in run_pipeline
    pipeline = pyemma.coordinates.pipeline(stages, chunksize = 1000)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/api.py", line 435, in pipeline
    p.parametrize()
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/pipelines.py", line 146, in parametrize
    element.estimate(element.data_producer, stride=self.param_stride)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/transform/tica.py", line 257, in estimate
    return super(TICA, self).estimate(X, **kwargs)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/transform/transformer.py", line 190, in estimate
    super(StreamingTransformer, self).estimate(X, **kwargs)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py", line 348, in estimate
    self._model = self._estimate(X)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/transform/tica.py", line 297, in _estimate
    self._diagonalize()
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/transform/tica.py", line 308, in _diagonalize
    eigenvalues, eigenvectors = eig_corr(self.cov, self.cov_tau, self.epsilon)
  File "/cbio/jclab/home/hansons/opt/anaconda/lib/python2.7/site-packages/pyEMMA-2.2.2-py2.7-linux-x86_64.egg/pyemma/util/linalg.py", line 151, in eig_corr
    assert np.allclose(C0.T, C0), 'C0 is not a symmetric matrix'
AssertionError: C0 is not a symmetric matrix
```

**Comment by jchodera** [comment]
The [relevant calling code](https://github.com/choderalab/msm-pipeline/blob/master/pipeline.py#L97-L101) is just:

``` python
    # do featurization + tICA by streaming over size-1000 "chunks"
    source = pyemma.coordinates.source(fnames, features = feat)
    tica = pyemma.coordinates.tica(lag = 10, kinetic_map = True, var_cutoff = 0.95)
    stages = [source, tica]
    pipeline = pyemma.coordinates.pipeline(stages, chunksize = 1000)
```

I don't think there's any reason to be getting an error like that from our end, though the number of features (13728) is quite large. 

Can you report this to the [pyemma issue tracker](https://github.com/markovmodel/PyEMMA/issues)?

**Comment by maxentile** [comment]
> though the number of features (13728) is quite large.

Quick note: this doesn't actually ask PyEMMA to compute a tICA projection using all ~14k contact features, [just the top `max_respairs=1000`](https://github.com/choderalab/msm-pipeline/blob/master/contact_features.py#L52-L55) of them.

**Comment by jchodera** [comment]
Ah, thanks!
